#!/bin/bash -e
APPID="yamoverflow"
SERVER="zure1.cloudapp.net"
TARGET="~/$APPID"
rsync -a --delete --exclude ".bundle" . "zure1.cloudapp.net:$TARGET/"
ssh -t "$SERVER" "cd $TARGET/ && sudo ./deployment/build.bash"

