#!/bin/bash -e
# Copyright (c) Microsoft Corporation
# All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# THIS CODE IS PROVIDED *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABLITY OR NON-INFRINGEMENT. 
#
# See the Apache Version 2.0 License for specific language governing permissions and limitations under the License. 
#
APPID="yamoverflow"
SERVER="zure1.cloudapp.net"
TARGET="~/$APPID"
rsync -a --delete --exclude ".bundle" --exclude "vendor" . "zure1.cloudapp.net:$TARGET/"
ssh -t "$SERVER" "cd $TARGET/ && sudo ./deployment/build.bash"

